config/routes.rb
Rails.application.routes.draw do

  resources :tournaments do
      resources :rounds 
  end

  get 'password_resets/new'

  get 'password_resets/edit'

  root 'static_pages#home'
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get  '/signup', to: 'users#new'
  get  '/login', to: 'sessions#new'
  post  '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]

end

app/models/tournament.rb
class Tournament < ApplicationRecord
  belongs_to :user
  has_many :rounds
  
  default_scope -> { order(event_start: :asc) }
  validates :user_id, presence: true
  validates :name, presence: true
  validates :num_rounds, presence: true, numericality: { other_than: 0}
end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user, only: [:destroy]

  def index
    @tournaments = Tournament.paginate(page: params[:page])
  end

  def show
    @tournament = Tournament.find(params[:id])
    @rounds = @tournament.rounds
  end

  def edit
    @tournament = Tournament.find(params[:id])
  end

  def update
    @tournament = Tournament.find(params[:id])
    if @tournament.update_attributes(tournament_params)
      flash[:success] = "Tournament Updated"
      redirect_to @tournament
    else
      render 'edit'
    end
  end

  def new
    @tournament = Tournament.new
  end

  def create
    @tournament = current_user.tournaments.build(tournament_params)
    if @tournament.save
      flash[:success] = "Tournament created."
      redirect_to @tournament
    else
      flash[:danger] = "Action Failed"
      render 'new'
    end
  end

  def destroy
        @tournament.destroy
        flash[:success] = "Tournament deleted"
        redirect_to current_user
  end

  private
    def tournament_params
      params.require(:tournament).permit(:name, :event_start, :num_rounds, :summary)
    end

    def correct_user
      @tournament = current_user.tournaments.find_by(id: params[:id])
      redirect_to root_url if @tournament.nil?
    end

end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/views/tournaments/_form.html.erb
<%= form_for(@tournament) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :event_start %>
  <%= f.datetime_select :event_start, class: 'form-control' %>

  <%= f.label :num_rounds %>
  <%= f.number_field :num_rounds, class: 'form-control' %>




  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/tournaments/_tournament.html.erb
<li id="tournament-<%= tournament.id %>">
<!--  <%= link_to gravatar_for(tournament.user, size: 50), tournament.user %>
  <span class="user">Organizer: <%= link_to tournament.user.name, tournament.user %></span>
  <span class="tname"><%= tournament.name %> | <%= tournament.num_rounds %></span>
  <span class="start"><%= tournament.event_start %></span>

  <span class="timestamp">
    Posted <%= time_ago_in_words(tournament.created_at) %> ago.
  </span>
</li> -->

<div class="card">
  <div class="card-block">
    <h4 class="card-title"><%= link_to tournament.name, tournament %></h4>
    <h6 class="card-subtitle mb-2 text-muted"><%= tournament.event_start %></h6>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <p class="card-link">Organizer: <%= tournament.user.name %></p>
    <% if current_user?(tournament.user) %>
      <%= link_to "delete", tournament, method: :delete,
                                       data: { confirm: "You sure?" } %>
    <% end %>
  </div>
</div>

</li>

app/views/tournaments/edit.html.erb
<% provide(:button_text, "Save Changes") %>
<h1>Edit Tournament</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/tournaments/index.html.erb
<h1>Upcoming Malifaux Tournaments</h1>

<%= will_paginate %>

<ul class="tournaments">
  <% @tournaments.each do |tournament| %>
    <%= render @tournaments %>
  <% end %>
</ul>

<%= will_paginate %>

app/views/tournaments/new.html.erb
<% provide(:button_text, "Create Tournament") %>
<h1>Create Tournament</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/tournaments/show.html.erb
<header>
    <h1><%= @tournament.name %></h1>
</header>
<h2><%= @tournament.event_start %> | <%= @tournament.location %> </h2>
<%= link_to("Edit Tournament", edit_tournament_path) %> | <%= link_to("All Tournaments", tournaments_path) %>

<p>
  <%= @tournament.summary %>
</p>
<h3>Cost</h3>
<p><%= @tournament.cost%></p>
<h3>Number of Rounds  <%= link_to("Add Round",new_tournament_round_path(@tournament)) %></h3>
<p><%= @tournament.num_rounds%></p>
<h3>Organizer</h3>
<p><%= @tournament.user.name %> </p>

<div class="col-md-8">

  <% if @tournament.rounds.any? %>
    <h3>Rounds (<%= @tournament.rounds.count %>)</h3>
    <ol class="rounds">
      <%= render @rounds %>
    </ol>
  <% end %>
</div>